### ISSUE TITLE
Question: How does the lazy start work? 

### ISSUE THREAD

**Issue by phil-opp** [yoshuawuyts/tasky#2]
The API docs claim that " `ParallelFuture` starts lazily". However, the implementation of `par` just seems to call `async_std::task::spawn`:

https://github.com/yoshuawuyts/parallel-future/blob/fe65333ff4910d84b1e85c9a5e6b5180013c6a1f/src/lib.rs#L126

This [`task::spawn`](https://docs.rs/async-std/latest/async_std/task/fn.spawn.html) function doesn't seem to be lazy (or at least it doesn't mention it in its docs).

So I'm a bit confused, how does this work?

**Comment by yoshuawuyts** [comment]
Oh hey! Yeah good catch; I messed that up when I rewrote the API surface two days ago.

It's no excuse, but I'm currently traveling and definitely didn't pay enough attention. With some luck I'll have a few spare mins later today to fix it. Ty for catching this!

**Comment by phil-opp** [comment]
Thanks! There's no hurry, I was just curious how you implemented this after reading your latest blog post.

**Comment by yoshuawuyts** [comment]
Published a patch version which fixes it!
